with open('c:/laragon/www/querys_tramas/aplicativo/app/bootstrap.php', 'a', encoding='utf-8') as f:
    f.write(' * 14_VERIFICAR_ASERTOS.py para mostrarlas como semáforo. Solo parseo de\n')
    f.write(' * presentación: la decisión PASS/FALLO la toma el script, no esta función.\n')
    f.write(' */\n')
    f.write('function parsearAserciones(string $salida): array\n')
    f.write('{\n')
    f.write('    $aserciones = [];\n')
    f.write('    foreach (explode("\\n", $salida) as $linea) {\n')
    f.write('        if (preg_match(\'/^(A1|A2|A3-ciclo|A3-CONTROL10|A4|A5|A6)\\s*\\[[^\\]]+\\]:\\s*(PASS|FALLO|SKIPPED)(.*)$/\', trim($linea), $m)) {\n')
    f.write('            $aserciones[] = [\'nombre\' => $m[1], \'estado\' => $m[2], \'detalle\' => trim($m[3], " -")];\n')
    f.write('        }\n')
    f.write('    }\n')
    f.write('    return $aserciones;\n')
    f.write('}\n')
